from datetime import datetime, timedelta

from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
from apscheduler.triggers.interval import IntervalTrigger
from sqlalchemy.orm import joinedload

from app.config import settings
from app.database import SessionLocal
from app.models.homework import Homework
from app.models.push_token import SentReminder
from app.models.user import User
from app.services.agent_bus_poller import poll_agent_bus
from app.services.attachment_storage import delete_attachment
from app.services.email import EmailUnavailableError, is_configured as email_is_configured, send_email
from app.services.ollama_agent import generate_email_reminder, generate_summary_for_user
from app.services.push import send_gentle_reminder

# How long before a deadline we send one calm heads-up (no repeated nagging, no alarm).
REMINDER_WINDOW = timedelta(hours=20, minutes=0)


async def run_daily_digest() -> None:
    """One relaxed evening summary per user, generated by the Ollama agent."""
    db = SessionLocal()
    try:
        users = db.query(User).filter(User.school_class_id.isnot(None), User.digest_enabled.is_(True)).all()
        for user in users:
            summary = await generate_summary_for_user(db, user)
            if summary:
                send_gentle_reminder(db, user.id, "Deine Hausaufgaben heute Abend", summary)
    finally:
        db.close()


async def run_deadline_reminders() -> None:
    """Gentle single reminder (push + optional AI-personalized email) for homework due soon
    that a user hasn't marked done yet."""
    db = SessionLocal()
    try:
        now = datetime.utcnow()
        window_end = now + REMINDER_WINDOW
        items = (
            db.query(Homework)
            .options(joinedload(Homework.subject), joinedload(Homework.completions))
            .filter(Homework.due_at >= now, Homework.due_at <= window_end)
            .all()
        )
        for hw in items:
            done_user_ids = {c.user_id for c in hw.completions}
            classmates = [u for u in hw.school_class.members if u.id not in done_user_ids]
            for user in classmates:
                already_sent = (
                    db.query(SentReminder)
                    .filter(SentReminder.homework_id == hw.id, SentReminder.user_id == user.id)
                    .first()
                )
                if already_sent:
                    continue
                if user.deadline_push_enabled:
                    send_gentle_reminder(
                        db,
                        user.id,
                        f"Erinnerung: {hw.subject.name}",
                        f"\"{hw.title}\" ist bald fällig - kein Stress, nur ein kleiner Hinweis.",
                    )
                if user.email_reminders_enabled and email_is_configured():
                    body = await generate_email_reminder(user, hw)
                    try:
                        send_email(user.email, f"Erinnerung: {hw.subject.name}", body)
                    except EmailUnavailableError:
                        pass  # never let a broken SMTP server block the push reminder/tracking
                db.add(SentReminder(homework_id=hw.id, user_id=user.id))
                db.commit()
    finally:
        db.close()


async def run_cleanup_old_homework() -> None:
    """Deletes homework items (and their attachment files) once they're old enough that
    nobody needs them anymore - regardless of whether anyone ever marked them done."""
    db = SessionLocal()
    try:
        cutoff = datetime.utcnow() - timedelta(days=settings.homework_cleanup_days)
        items = db.query(Homework).options(joinedload(Homework.attachments)).filter(Homework.due_at < cutoff).all()
        for hw in items:
            attachment_ids = [a.id for a in hw.attachments]
            db.delete(hw)
            db.commit()
            for attachment_id in attachment_ids:
                delete_attachment(attachment_id)
    finally:
        db.close()


def start_scheduler() -> AsyncIOScheduler:
    scheduler = AsyncIOScheduler()
    # Pass the coroutine functions directly - AsyncIOScheduler detects iscoroutinefunction()
    # and runs them straight on the running event loop. Wrapping them in
    # `lambda: asyncio.create_task(...)` (as this used to do) makes APScheduler treat the job as
    # a plain blocking callable instead, dispatching it to its default thread-pool executor -
    # there's no running event loop in that thread, so asyncio.create_task() always raised
    # "RuntimeError: no running event loop" and the job silently never ran.
    scheduler.add_job(
        run_daily_digest,
        CronTrigger(hour=settings.digest_hour_local, minute=0),
        id="daily_digest",
        replace_existing=True,
    )
    scheduler.add_job(
        run_deadline_reminders,
        IntervalTrigger(hours=1),
        id="deadline_reminders",
        replace_existing=True,
    )
    # Always registered - which users (if any) have connected their own OwnAI account is a DB
    # query inside poll_agent_bus() itself, not a single global on/off switch.
    scheduler.add_job(
        poll_agent_bus,
        IntervalTrigger(seconds=settings.ownai_agent_bus_poll_seconds),
        id="agent_bus_poll",
        replace_existing=True,
    )
    scheduler.add_job(
        run_cleanup_old_homework,
        CronTrigger(hour=3, minute=30),
        id="cleanup_old_homework",
        replace_existing=True,
    )
    scheduler.start()
    return scheduler
