import asyncio
from datetime import datetime, timedelta

from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
from apscheduler.triggers.interval import IntervalTrigger
from sqlalchemy.orm import joinedload

from app.config import settings
from app.database import SessionLocal
from app.models.homework import Homework
from app.models.push_token import SentReminder
from app.models.user import User
from app.services import agent_bus_client
from app.services.agent_bus_poller import poll_agent_bus
from app.services.email import EmailUnavailableError, is_configured as email_is_configured, send_email
from app.services.ollama_agent import generate_email_reminder, generate_summary_for_user
from app.services.push import send_gentle_reminder

# How long before a deadline we send one calm heads-up (no repeated nagging, no alarm).
REMINDER_WINDOW = timedelta(hours=20, minutes=0)


async def run_daily_digest() -> None:
    """One relaxed evening summary per user, generated by the Ollama agent."""
    db = SessionLocal()
    try:
        users = db.query(User).filter(User.school_class_id.isnot(None), User.digest_enabled.is_(True)).all()
        for user in users:
            summary = await generate_summary_for_user(db, user)
            if summary:
                send_gentle_reminder(db, user.id, "Deine Hausaufgaben heute Abend", summary)
    finally:
        db.close()


async def run_deadline_reminders() -> None:
    """Gentle single reminder (push + optional AI-personalized email) for homework due soon
    that a user hasn't marked done yet."""
    db = SessionLocal()
    try:
        now = datetime.utcnow()
        window_end = now + REMINDER_WINDOW
        items = (
            db.query(Homework)
            .options(joinedload(Homework.subject), joinedload(Homework.completions))
            .filter(Homework.due_at >= now, Homework.due_at <= window_end)
            .all()
        )
        for hw in items:
            done_user_ids = {c.user_id for c in hw.completions}
            classmates = [u for u in hw.school_class.members if u.id not in done_user_ids]
            for user in classmates:
                already_sent = (
                    db.query(SentReminder)
                    .filter(SentReminder.homework_id == hw.id, SentReminder.user_id == user.id)
                    .first()
                )
                if already_sent:
                    continue
                if user.deadline_push_enabled:
                    send_gentle_reminder(
                        db,
                        user.id,
                        f"Erinnerung: {hw.subject.name}",
                        f"\"{hw.title}\" ist bald fällig - kein Stress, nur ein kleiner Hinweis.",
                    )
                if user.email_reminders_enabled and email_is_configured():
                    body = await generate_email_reminder(user, hw)
                    try:
                        send_email(user.email, f"Erinnerung: {hw.subject.name}", body)
                    except EmailUnavailableError:
                        pass  # never let a broken SMTP server block the push reminder/tracking
                db.add(SentReminder(homework_id=hw.id, user_id=user.id))
                db.commit()
    finally:
        db.close()


def start_scheduler() -> AsyncIOScheduler:
    scheduler = AsyncIOScheduler()
    scheduler.add_job(
        lambda: asyncio.create_task(run_daily_digest()),
        CronTrigger(hour=settings.digest_hour_local, minute=0),
        id="daily_digest",
        replace_existing=True,
    )
    scheduler.add_job(
        lambda: asyncio.create_task(run_deadline_reminders()),
        IntervalTrigger(hours=1),
        id="deadline_reminders",
        replace_existing=True,
    )
    if agent_bus_client.is_configured():
        scheduler.add_job(
            lambda: asyncio.create_task(poll_agent_bus()),
            IntervalTrigger(seconds=settings.ownai_agent_bus_poll_seconds),
            id="agent_bus_poll",
            replace_existing=True,
        )
    scheduler.start()
    return scheduler
