"""add agent_tone to users

Revision ID: 4cebde78333a
Revises: b12609cf0440
Create Date: 2026-09-18 18:51:18.378686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cebde78333a'
down_revision: Union[str, None] = 'b12609cf0440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows on the column add; kept permanently
    # since dropping a column default isn't portable across SQLite/Postgres in one
    # statement, and leaving it is harmless (the ORM still sets it explicitly too).
    op.add_column(
        'users', sa.Column('agent_tone', sa.String(length=16), nullable=False, server_default='locker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agent_tone')
    # ### end Alembic commands ###
