"""flashcard decks with per-user spaced repetition

Revision ID: 8fbf1c673649
Revises: 4cebde78333a
Create Date: 2026-09-20 13:47:07.549116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbf1c673649'
down_revision: Union[str, None] = '4cebde78333a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_decks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('school_class_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcard_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flashcard_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flashcard_id', 'user_id', name='uq_progress_flashcard_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard_progress')
    op.drop_table('flashcards')
    op.drop_table('flashcard_decks')
    # ### end Alembic commands ###
