"""superadmin tables and class cascade deletes

Revision ID: b12609cf0440
Revises: 85d3cfe2fc8b
Create Date: 2026-09-18 18:48:55.635988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12609cf0440'
down_revision: Union[str, None] = '85d3cfe2fc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admin_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nonce_b64', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super_admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_admins')
    op.drop_table('super_admin_challenges')
    # ### end Alembic commands ###
